SELECT a.AUTHOR_ID, a.AUTHOR_NAME, b.CATEGORY, SUM(bs.SALES * b.PRICE) AS TOTAL_SALES
FROM BOOK b
JOIN AUTHOR a
    ON b.AUTHOR_ID = a.AUTHOR_ID
JOIN BOOK_SALES bs
    ON bs.BOOK_ID = b.BOOK_ID
WHERE YEAR(bs.SALES_DATE) = 2022 and MONTH(bs.SALES_DATE) = 1
GROUP BY a.AUTHOR_ID, b.CATEGORY
ORDER BY a.AUTHOR_ID,b.CATEGORY DESC