SELECT date_format(SALES_DATE,'%Y-%m-%d') as SALES_DATE, PRODUCT_ID, USER_ID, SALES_AMOUNT
FROM ONLINE_SALE ons
WHERE YEAR(ons.SALES_DATE) = 2022 AND MONTH(ons.SALES_DATE) = 3

UNION

SELECT date_format(SALES_DATE,'%Y-%m-%d') as SALES_DATE, PRODUCT_ID, NULL AS USER_ID, SALES_AMOUNT
FROM OFFLINE_SALE offs
WHERE YEAR(offs.SALES_DATE) = 2022 AND MONTH(offs.SALES_DATE) = 3

ORDER BY SALES_DATE, PRODUCT_ID, USER_ID