SELECT fp.PRODUCT_ID, fp.PRODUCT_NAME, SUM(fp.PRICE*fo.AMOUNT) as TOTAL_SALES
FROM FOOD_PRODUCT fp
JOIN FOOD_ORDER fo
ON fp.PRODUCT_ID = fo.PRODUCT_ID
WHERE YEAR(PRODUCE_DATE) = 2022 and MONTH(PRODUCE_DATE) = 5
GROUP BY fp.PRODUCT_ID
ORDER BY TOTAL_SALES DESC, fp.PRODUCT_ID