SELECT 
    crcrh.HISTORY_ID,
    ROUND(
        (DATEDIFF(crcrh.END_DATE, crcrh.START_DATE)+1) * crcc.DAILY_FEE * (1 - IFNULL(crcdp.DISCOUNT_RATE, 0) / 100),
        0
    ) AS FEE
FROM CAR_RENTAL_COMPANY_CAR crcc
JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY crcrh 
    ON crcc.CAR_ID = crcrh.CAR_ID
LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN crcdp
    ON crcc.CAR_TYPE = crcdp.CAR_TYPE
   AND CAST(SUBSTRING_INDEX(crcdp.DURATION_TYPE, '일', 1) AS UNSIGNED) =
       CASE 
           WHEN DATEDIFF(crcrh.END_DATE, crcrh.START_DATE)+1 >= 90 THEN 90
           WHEN DATEDIFF(crcrh.END_DATE, crcrh.START_DATE)+1 >= 30 THEN 30
           WHEN DATEDIFF(crcrh.END_DATE, crcrh.START_DATE)+1 >= 7  THEN 7
       END
WHERE crcc.CAR_TYPE = '트럭'
ORDER BY FEE DESC, crcrh.HISTORY_ID DESC;
