SELECT u.USER_ID, NICKNAME, SUM(PRICE) as TOTAL_SALES
FROM USED_GOODS_BOARD b JOIN USED_GOODS_USER u
ON b.WRITER_ID = u.USER_ID
where STATUS = 'DONE'
group by u.USER_ID
having SUM(PRICE) >= 700000 
order by TOTAL_SALES