SELECT mp.MEMBER_NAME, rr.REVIEW_TEXT, date_format(rr.REVIEW_DATE,'%Y-%m-%d') as REVIEW_DATE
FROM MEMBER_PROFILE mp
RIGHT JOIN REST_REVIEW rr
ON mp.MEMBER_ID = rr.MEMBER_ID
WHERE rr.MEMBER_ID =  (
    SELECT MEMBER_ID
    FROM REST_REVIEW
    GROUP BY MEMBER_ID
    ORDER BY COUNT(*) DESC
    LIMIT 1
)
ORDER BY rr.REVIEW_DATE, rr.REVIEW_TEXT