SELECT
    SUM(hg.SCORE) AS SCORE,
    he.EMP_NO,
    he.EMP_NAME,
    he.POSITION,
    he.EMAIL
  
FROM HR_DEPARTMENT hd
INNER JOIN HR_EMPLOYEES he ON hd.DEPT_ID = he.DEPT_ID
INNER JOIN HR_GRADE hg ON he.EMP_NO = hg.EMP_NO
GROUP BY he.EMP_NO, he.EMP_NAME, he.POSITION, he.EMAIL
ORDER BY SCORE DESC
LIMIT 1;

